spring:
  ai:
    openai:
      api-key: # 본인 ChatGPT API Key
      chat:
        options:
          model: gpt-4o # 사용할 모델 (gpt-4, gpt3.5, gpt-4o 등등 모델)
          temperature: 0.7
      image:
        options:
          model: dall-e-3 # 이미지 생성 모델